### ISSUE TITLE
.issues not aligning center

### ISSUE THREAD

**Issue by kmatsu0402** [kmatsu0402/app-issueboard#1]
Want to have <code>.issues</code> elements aligned in center of containing div element.

Both of the following seem to not have any affect.
```css
 align-content: center;
 justify-content: center;
```

**Comment by kmatsu0402** [comment]
Fixed with the following.
```css
foo {
   display: flex;
   flex-flow: column nowrap;
   align-items: center;
}
```
